./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10009.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10009.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10014.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10014.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10030.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10030.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10069.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10069.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10070.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10070.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10105.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10105.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10130.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10130.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10146.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10146.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10276.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10276.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10281.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10281.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10282.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10282.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10284.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10284.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10287.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10287.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10301.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10301.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10306.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10306.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10319.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10319.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10323.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10323.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10328.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10328.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10331.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10331.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10378.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10378.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10392.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10392.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10395.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10395.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10396.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10396.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10398.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10398.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10413.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10413.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10431.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10431.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10435.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10435.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10436.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10436.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10441.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10441.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10443.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10443.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10453.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10453.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10485.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10485.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10489.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10489.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10512.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10512.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10520.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10520.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10521.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10521.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10527.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10527.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10533.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10533.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10543.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10543.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10546.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10546.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10575.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10575.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10581.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10581.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10583.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10583.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10602.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10602.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10613.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10613.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10615.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10615.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10624.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10624.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10664.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10664.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10680.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10680.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10690.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10690.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10708.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10708.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10758.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10758.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10762.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10762.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10768.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10768.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10786.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10786.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10812.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10812.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10820.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10820.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10844.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10844.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10852.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10852.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10855.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10855.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10863.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10863.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10902.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10902.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10907.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10907.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10921.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10921.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10927.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10927.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10931.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10931.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10935.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10935.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10946.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10946.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10965.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10965.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10972.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10972.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10976.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10976.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10979.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10979.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10980.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10980.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10990.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10990.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/10998.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/10998.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/11054.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/11054.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/11063.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/11063.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/11133.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/11133.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/11136.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/11136.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/11139.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/11139.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/11152.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/11152.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/11155.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/11155.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/20009.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/20009.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/20018.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/20018.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/20028.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/20028.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/20030.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/20030.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/20052.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/20052.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/20069.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/20069.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/20105.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/20105.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/20127.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/20127.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/20145.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/20145.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/20146.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/20146.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/20277.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/20277.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/20282.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/20282.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/20284.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/20284.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/20306.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/20306.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/20307.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/20307.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/20314.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/20314.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/20322.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/20322.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Fut/20395.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase2/Fut/20395.xyt
