./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10009.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/20395.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10014.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/20322.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10030.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/20314.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10069.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/20307.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10070.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/20306.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10105.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/20284.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10130.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/20282.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10146.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/20277.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10276.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/20146.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10281.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/20145.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10282.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/20127.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10284.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/20105.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10287.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/20069.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10301.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/20052.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10306.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/20030.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10319.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/20028.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10323.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/20018.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10328.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/20009.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10331.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/11155.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10378.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/11152.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10392.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/11139.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10395.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/11136.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10396.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/11133.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10398.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/11063.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10413.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/11054.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10431.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10998.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10435.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10990.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10436.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10980.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10441.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10979.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10443.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10976.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10453.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10972.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10485.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10965.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10489.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10946.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10512.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10935.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10520.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10931.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10521.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10927.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10527.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10921.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10533.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10907.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10543.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10902.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10546.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10863.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10575.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10855.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10581.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10852.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10583.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10844.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10602.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10820.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10613.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10812.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10615.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10786.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10624.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10768.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10664.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10762.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10680.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10758.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10690.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10708.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10708.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10690.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10758.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10680.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10762.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10664.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10768.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10624.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10786.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10615.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10812.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10613.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10820.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10602.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10844.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10583.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10852.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10581.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10855.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10575.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10863.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10546.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10902.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10543.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10907.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10533.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10921.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10527.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10927.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10521.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10931.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10520.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10935.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10512.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10946.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10489.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10965.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10485.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10972.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10453.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10976.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10443.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10979.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10441.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10980.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10436.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10990.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10435.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/10998.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10431.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/11054.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10413.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/11063.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10398.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/11133.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10396.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/11136.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10395.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/11139.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10392.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/11152.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10378.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/11155.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10331.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/20009.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10328.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/20018.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10323.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/20028.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10319.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/20030.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10306.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/20052.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10301.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/20069.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10287.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/20105.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10284.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/20127.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10282.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/20145.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10281.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/20146.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10276.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/20277.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10146.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/20282.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10130.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/20284.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10105.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/20306.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10070.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/20307.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10069.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/20314.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10030.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/20322.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10014.xyt
./matcher.py	/media/Data/august_data/XYT_TEMPLATES/Phase1/Lum/20395.xyt	/media/Data/august_data/XYT_TEMPLATES/Phase1/Sec/10009.xyt
